[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node dist/index-cloud.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
